# Authors

Fields for author information, academic history, and impact measures are included in the authors' table.
This table contains 253144301 rows.
The fields are listed in the table below.

```{r aut_show_table,results='asis'}
aut_fields = read_excel("../data/datasetsFields/authors.xlsx")
# aut_fields %>% 
#   gt() %>% 
#   tab_header(title = md("**Authors** Table Schema")) %>% 
#   tab_source_note(
#         source_note = md("*Description is taken from  [Aminer](https://www.aminer.cn/oag-2-1)*")
#     ) %>% 
#   cols_width(starts_with("Ex") ~ px(75))
aut_fields %>% 
  kbl(booktabs = T,caption = "Authors Table Schema") %>% 
  kable_styling(latex_options = c("hold_position", "scale_down"))
```

## Citation Overview

```{r citation_pubs_count}
citation_pubs_count = read_csv("../data/n_citation_n_pubs_count.csv/part-00000-eb38c2e9-3b79-4c73-8310-58299c029e69-c000.csv")
```

```{r citation_count}
citation_pubs_count %>% 
  group_by(n_citation) %>% 
  summarise(count = sum(count)) %>% 
  arrange(-count) %>% 
  mutate(percent = count/sum(count))-> citation_count
```

```{r citation_count_show_table}
citation_count %>% 
  head(10) %>% 
  gt() %>% 
  fmt_percent(columns = c("percent"), decimals = 1) %>% 
  cols_align(
    align = "center",
    columns = c("n_citation")
  ) %>% 
  cols_label(
    n_citation = "Number of Citation",
    count = "Frequency",
    percent = "Percent Share"
  ) %>% 
    tab_header(title = md("The Top 10 Frequency of Total Authors' Citations"))

```

```{r citation_count_bar_plot,fig.height=4,fig.cap = "The Frequency of Authors by Number of Total Citations"}
ggplot(subset(citation_count,n_citation>0 & n_citation<100),aes(x = n_citation, y = count))+
  geom_col(fill = prettyRed,color = "transparent")+
  theme_scientific()+
  scale_y_continuous(labels = scales::comma)+
  labs(x = " Number of Citations", y = "Number of Authors")
```

```{r citation_count_density_plot,fig.height=4,fig.cap = "The Frequency of Authors by Number over Total Citations 100"}
breaks = c(100,200,500,1000,2000,5000,10000,20000,50000,100000,200000)
labels = pretty_number(breaks)
citation_count %>% 
  filter(n_citation>=100) %>%
  arrange(n_citation) %>% 
ggplot(aes(x = n_citation, y = count))+
  geom_line(color = prettyRed,fill = "transparent")+
  theme_scientific()+
  scale_y_continuous(labels = scales::comma,breaks = 5000*(0:10))+
  scale_x_continuous(trans = "log",
                     breaks = breaks,labels = labels)+
  labs(x = " Number of Citations", y = "Number of Authors")
```


```{r strange_jump_n_citation,fig.height=4,fig.cap="Strange Jump in Total Citations Density Function"}
citation_count %>% 
  filter(n_citation>=2000 & n_citation<3000) %>%
  arrange(n_citation) %>% 
ggplot(aes(x = n_citation, y = count))+
  geom_line(color = prettyRed,fill = "transparent")+
  theme_scientific()+
  labs(x = " Number of Citations", y = "Number of Authors")

```



```{r citation_count_tail_density_plot,fig.height=4,fig.cap="Tail Distribution of Authors over Total Citations 100"}
citation_count %>% 
  filter(n_citation>=100) %>%
  arrange(-n_citation) %>% 
  mutate(total = cumsum(count)) %>% 
  ggplot(aes(x = n_citation, y = total))+
    geom_line(color = prettyRed,fill = "transparent")+
    theme_scientific()+
    scale_y_continuous(breaks = 600000*(0:11),labels = pretty_number(600000*(0:11)))+
    scale_x_continuous(trans = "log",
                     breaks = breaks,labels = labels)+
    labs(x = " Number of Citations", y = "Number of Authors")
```

## Number of Publication


```{r n_pubs_count}
citation_pubs_count %>% 
  group_by(n_pubs) %>% 
  summarise(count = sum(count)) %>% 
  arrange(-count) %>% 
  mutate(percent = count/sum(count))-> n_pubs_count
```

```{r n_pubs_count_show_table}
n_pubs_count %>% 
  head(10) %>% 
  gt() %>% 
  fmt_percent(columns = c("percent"), decimals = 1) %>% 
  cols_label(
    n_pubs = "Number of Publication",
    count = "Frequency",
    percent = "Percent Share"
  ) %>% 
    tab_header(title = md("The Top 10 Frequency of Total Number of Authors' Publications.")) %>% 
    cols_align(
    align = "center",
    columns = c("n_pubs")
  )
```

```{r n_pubs_count_bar_plot,fig.height=4,fig.cap = "The Frequency of Authors by Number of Total Publications"}
breaks = c(1,2,5,10,20,50,100,200,500,1000,2000,5000,10000,20000,50000,100000,200000)*1000
labels = pretty_number(breaks)

ggplot(subset(n_pubs_count,n_pubs>0 & n_pubs<200),aes(x = n_pubs, y = count))+
  geom_col(fill = prettyRed,color = "transparent")+
  theme_scientific()+
  scale_y_continuous(breaks = breaks, labels = labels,trans = "log10")+
  coord_cartesian(ylim = c(1000,NA))+
  labs(x = "Number of Publications", y = "Number of Authors")
```

```{r,fig.width=8,fig.height=8}
breaks = 10^seq(0,10)
labels = pretty_number(breaks)
citation_pubs_count %>% 
  filter(n_citation<20000 & n_pubs<1000) %>%
  mutate(
    nc = 200*ceiling(n_citation/200),
    np = 10*ceiling(n_pubs/10)
    ) %>% 
  group_by(nc,np) %>% 
  summarise(count = sum(count)) %>% 
  ggplot(aes(x = nc, y = np,fill = count))+
  geom_tile()+
  scale_fill_gradientn(colours = c("gray90","#116656",prettyRed,"gray20","gray10"),
                       breaks = breaks,labels = labels,
                       trans = "log10",na.value = "grey90")+
  labs(x = "Number of Citations",y = "Number of Publications")+
  theme_scientific()+
  bottom_legend()
```

